import assert from 'node:assert/strict';
export async function checkFinalSmoke(browser,base){
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});
 const page=await context.newPage();page.setDefaultTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base,{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Open chapters'}).click();await page.locator('#chapter-menu a[href="#explore"]').click();
 await page.waitForFunction(()=>Math.abs(document.getElementById('explore').getBoundingClientRect().top)<20);
 await page.getByRole('button',{name:'Explore project',exact:true}).tap();
 await page.waitForFunction(()=>document.querySelector('.webgl').__sceneDiagnostics?.mode==='explore');
 const read=()=>page.evaluate(()=>structuredClone(document.querySelector('.webgl').__sceneDiagnostics));
 const before=(await read()).target;
 await page.keyboard.press('ArrowRight');await page.waitForTimeout(400);
 assert.notDeepEqual((await read()).target,before,'Keyboard panning must work');
 await page.getByRole('button',{name:'Reset View',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.webgl').__sceneDiagnostics.mode==='explore');
 await page.locator('[data-hotspot-id="p05"]').tap();
 await page.waitForFunction(()=>document.querySelector('.webgl').__sceneDiagnostics.mode==='explore');
 await page.waitForFunction(()=>document.querySelector('.hotspot-card img')?.naturalWidth===1200);
 assert((await page.locator('.hotspot-card img').getAttribute('src')).endsWith('/hotspots/p05.webp'));
 const sizes=await page.locator('.scene-stage button:visible').evaluateAll(buttons=>buttons.map(b=>({name:b.getAttribute('aria-label')||b.textContent,width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height})));
 assert(sizes.every(b=>b.width>=43.9&&b.height>=43.9),'Explore touch targets must be 44px');
 await page.screenshot({path:'qa/mobile-final-hotspot.png',scale:'css'});
 await page.getByRole('button',{name:'Exit Explore',exact:true}).tap();
 await page.waitForFunction(()=>document.querySelector('.webgl').__sceneDiagnostics.mode==='guided'&&document.body.style.position==='');
 assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Explore project');
 await page.getByRole('button',{name:'Explore project',exact:true}).tap();
 await page.waitForFunction(()=>document.querySelector('.webgl').__sceneDiagnostics.mode==='explore');
 await page.keyboard.press('Escape');
 await page.waitForFunction(()=>document.querySelector('.webgl').__sceneDiagnostics.mode==='guided'&&document.body.style.position==='');
 assert.deepEqual(errors,[]);await context.close();
 return {build:'production',directExploreFromImageMode:true,p05SourceImage:true,keyboardPan:true,touchTargets44px:true,exitExplore:true,escape:true,focusRestored:true,errors};
}
